CREATE DATABASE  `Shahrukh` ;

CREATE TABLE IF NOT EXISTS `Shahrukh`.`tbl_demo5` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image_url` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;